### ISSUE TITLE
Based on faulty logic

### ISSUE THREAD

**Issue by kanoi** [2miners/stratum-ping#19]
Sorry, this program is based on faulty logic.
The time to connect to a pool depends on the configuration and code for the pool.
The relevance of that number may well be meaningless depending on how the pool works.
As an example, a remote node using ckpool, timestamps the shares when they arrive at the remote node, since that remote node will also immediately submit a block if that share is a block also.
Thus all that matters is the ping to the remote node, not some random number related to connecting to the pool.
If you check the source code and configuration of every pool, you would find that for some, if not many, this program's output is providing false information and thus is detrimental to the person using it.

**Comment by jon4hz** [comment]
I agree with this. 
The initial subscription to the pool can be much slower than the actual mining. 
For example if the pool has a ban manager or has some dependencies for address validation e.g.

Such factors will add a delay to the initial subscription but wont have any effect once the connection stands. 

Testing the latency against a specific pool port makes sense though. Otherwise pools could "cheat" simply by answering the ping directly from a lb instead of the actual stratum server.
